### ISSUE TITLE
Date picker default

### ISSUE THREAD

**Issue by ps2** [WildflowerSchools/sensei#56]
<img width="725" alt="developer_tools_-_http___localhost_3000_s_3_networks_wf_events_insights_classroom_id_1" src="https://cloud.githubusercontent.com/assets/14649/26650065/dee942e0-460d-11e7-8058-ae30e8fc70e2.png">

 When I bring up the insights interface initially, the current day is selected, which is correct, but when I choose Visualization, and Viewpoint, I get no data.  If I manually select today's date, I then get data.   The above image shows how the requests differ.  Looks like the hour changes.

**Comment by marknutter** [comment]
fixed in `activity-summary-viz`
